### ISSUE TITLE
Documentation on available input and lead times

### ISSUE THREAD

**Issue by seangtkelley** [NASA-IMPACT/Prithvi-WxC#35]
I'm attempting to use this notebook for rollout: https://github.com/NASA-IMPACT/Prithvi-WxC/blob/develop/examples/PrithviWxC_rollout.ipynb and I want to try some different input and lead times. For example, 
```py
lead_time = 48
input_time = -12
```
However, most of the time I get error: `"There doesn't seem to be any valid data."`

Is there a good resource to find what combinations of input and lead times are available?

**Comment by WillTrojak** [comment]
You may need to modify the number of MERRA2 data files you've downloaded. The data loader will look at the files you have and will only produce samples for which you have the data. For example, if you've only downloaded one day of data, then you can't use a lead time of 48 hours as there would be no way to get the target. 

This also highlights something that we need to add to the dataloader: an inference flag.
